---
- name: Arista Set Hostname
  hosts: arista_routers
  gather_facts: no

  tasks: 
  - name: Set Router Hostname
    arista.eos.eos_hostname:
      config:
        hostname: arista-prod-router-3
      state: merged 
