---
- name: Arista Set Banner
  hosts: arista_routers
  gather_facts: no

  tasks: 
  - name: Set Banner for Arista Router
    arista.eos.eos_banner:
      banner: login
      text: |
        Warning!!!! This system is restricted by Red Hat Inc. This is a Development Network System. This system is being monitored for all suspicious and malicious activity! Created by Ansible Automation Platform
      state: present  
